baseURL: example.com
languageCode: en-us
title: R-curious
theme: archie
copyright: © Rashid
pygmentsstyle: monokai
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
params:
  mode: auto
  social:
    - icon: github
      name: GitHub
      url: https://github.com/rbaset5
    - icon: twitter
      name: Twitter
      url: https://twitter.com/rashidbaset
    - icon: gitlab
      name: GitLab
      url: https://gitlab.com/rbaset5/
  subtitle: A blog exploring the intersections of R and sociology, economics, and business.
  useCDN: no
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
