[build]
command = "hugo"
context = "production"
publish = "public"
[context.production.envrionment]
HUGO_VERSION = "0.81.0" 
HUGO_ENV = "production"
#[build.environment]
#HUGO_VERSION = "0.81.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"
